### ISSUE TITLE
compile on macOS

### ISSUE THREAD

**Issue by wusan1234** [jhhung/EARRINGS#5]
Dear,

    I wanna try to install EARRINGS in my Mac, when I executed `cmake --build . --target install`, errors were showed below:

<img width="1440" alt="截屏2021-12-09 下午4 24 00" src="https://user-images.githubusercontent.com/74703924/145361473-0b43716e-554c-4f8b-8720-777174104ed9.png">
<img width="1440" alt="截屏2021-12-09 下午4 24 05" src="https://user-images.githubusercontent.com/74703924/145361496-21699a2c-f1be-41fb-8f50-debabbeef423.png">
<img width="1440" alt="截屏2021-12-09 下午4 25 21" src="https://user-images.githubusercontent.com/74703924/145361510-656fc939-c001-496a-8b69-f3442c37992d.png">
<img width="1440" alt="截屏2021-12-09 下午4 25 26" src="https://user-images.githubusercontent.com/74703924/145365106-0a2cc58b-d085-4f19-9670-80743fe1daea.png">
<img width="1440" alt="截屏2021-12-09 下午4 25 29" src="https://user-images.githubusercontent.com/74703924/145365741-3f2c0c70-5d04-4f86-b960-eefe8dd4465a.png">

**Comment by jhhung** [comment]
Hi, it appears that you didn't have the right libraries.
What is the version of your compiler? Please use gcc 8.0 for now. 

We will support versions above 8.0 in our next release.

**Comment by joyeli** [comment]
@wusan1234 
We have already updated our EARRINGS to support gcc 8 or higher (to gcc 11), please pull and rebuild everything, including the hunter toolchain. If you still get the same error with our new update, please feel free to reopen this thread to discuss it.
